name: Build Tweak

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          export THEOS="$GITHUB_WORKSPACE/theos"
          git clone --recursive https://github.com/theos/theos.git $THEOS
          git -C $THEOS/sdks pull
          brew install ldid

      - name: Build
        run: |
          export THEOS="$GITHUB_WORKSPACE/theos"
          make clean
          make package

      - name: Upload deb & dylib
        uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: |
            packages/*.deb
            .theos/obj/*.dylib
